### ISSUE TITLE
改行コードが混じっていると改行コードが消える

### ISSUE THREAD

**Issue by itizawa** [zahmis/spacer#1]
![スクリーンショット 2023-05-09 18 36 15](https://user-images.githubusercontent.com/48426654/237056832-ec9e5b4b-45f2-48ac-b6ef-3b47bedb635e.png)
![スクリーンショット 2023-05-09 18 36 32](https://user-images.githubusercontent.com/48426654/237056898-33175ad1-1910-419a-badd-1d34dc05c11a.png)

### input
```
## 改行テスト
ここでtestします
```
### output
```
## 改行テスト ここで test します
```

## 想定する挙動
```
## 改行テスト 
ここで test します
```

**Comment by zahmis** [comment]
Fixed
